services:
  - type: web
    name: jyotsna-ncbi
    env: node
    buildCommand: npm install
    startCommand: node app.js
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
      - key: NODE_ENV
        value: production
    autoDeploy: true 